---
- name: Check disk space on the target server
  hosts: remote_server
  tasks:
    - name: Run df -h to check disk space
      command: df -h
      register: disk_output

    - name: Display disk space output
      debug:
        var: disk_output.stdout

