---
- name: Create folders on the remote server
  hosts: remote_server
  tasks:
    - name: Ensure the folders exist
      ansible.builtin.file:
        path: /home/musab/{{ item }}
        state: directory
        mode: '0755'
      loop:
        - folder1
        - folder2

